apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: 2482569sproject
spec:
  selector:
    app: redis
  ports:
    - name: redis-port
      port: 6379
      protocol: TCP
      targetPort: 6379
