import { MouseEvent } from 'react';
import apiClient from '../util/api-client';
import { shallow } from 'zustand/shallow';
import { DiffusionState, useGlobalStore } from '../store/global.store';
import { useFormStore } from '../store/form.store';
import ProgressBar from './ProgressBar';
import ImageSlider from './ImageSlider';

export default function TextToImage() {
  const [prompt, setPrompt, steps, setSteps] = useFormStore(
    (state) => [state.prompt, state.setPrompt, state.steps, state.setSteps],
    shallow
  );

  const [
    setProgress,
    setImage,
    progress,
    images,
    diffusionState,
    selectedImage,
  ] = useGlobalStore(
    (state) => [
      state.setProgress,
      state.setImage,
      state.progress,
      state.images,
      state.diffusionState,
      state.selectedImage,
    ],
    shallow
  );

  const handleSubmit = (event: MouseEvent<HTMLFormElement>) => {
    event.preventDefault();
    setImage(undefined);
    setProgress(0);
    apiClient.post('/generators/text-to-image', {
      userId: 1,
      args: {
        prompt,
        steps,
        height: 512,
        width: 512,
      },
    });
  };

  return (
    <>
      <div className='px-3 mb-6 md:mb-0'>
        <div className='max-w-md p-1 rounded-lg border-4 border-dashed border-gray-200'>
          <img src={images[selectedImage]} alt='Generated by user' />
          <ImageSlider />
        </div>
      </div>
      <div className='w-full md:w-1/3 md:min-w-[33%] mb-6 md:mb-0'>
        <form className='w-full max-w-lg' onSubmit={handleSubmit}>
          <label
            className='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'
            htmlFor='generator-prompt'
          >
            Text Prompt
          </label>
          <input
            className='appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white'
            id='generator-prompt'
            type='text'
            placeholder='Mount Fuji with rising sun'
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
          />
          <label
            className='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'
            htmlFor='generator-steps'
          >
            Steps
          </label>
          <input
            className='appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white'
            id='generator-steps'
            type='number'
            value={steps}
            onChange={(e) => setSteps(+e.target.value)}
          />
          <button
            className='bg-purple-500 hover:bg-purple-400 text-white font-bold py-2 px-4 rounded disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200'
            type='submit'
            disabled={diffusionState === DiffusionState.IN_PROGRESS}
          >
            Generate
          </button>
          <ProgressBar className='pt-5' percentage={progress} />
        </form>
      </div>
    </>
  );
}
